/*
 * ReportCost.java
 *
 * Created on Sep 7, 2011, 8:58:38 AM
 */
package com.provident.ui;

import com.provident.proses.CostPerformance;
import com.provident.util.DBConnection;
import java.io.IOException;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jxls.exception.ParsePropertyException;
import org.apache.log4j.Logger;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.joda.time.DateTime;

/**
 *
 * @author Christian
 */
public class ReportCost extends javax.swing.JFrame {

    private static Logger log = Logger.getLogger(ReportCost.class);
    
    private String [] perusahaan;
    private String [] inisialPerusahaan;
    private String [] bulan = {"Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"};
   
    /** Creates new form ReportCost */
    public ReportCost() {
        initComponents();
        this.setLocationRelativeTo(null);
        initialize();
        cboPerusahaan.setModel(new DefaultComboBoxModel(perusahaan));
        cboBulan.setModel(new DefaultComboBoxModel(bulan));
    }
    
    //Initialize Data di Combo Box
    private void initialize(){
        Properties config = DBConnection.loadProperties("config.properties");
        perusahaan = config.getProperty("perusahaan").split(",");
        inisialPerusahaan = config.getProperty("company").split(",");
        
        DateTime now = new DateTime();
        for(int i=0; i<5; i++){
            cboTahun.addItem(now.getYear() - i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParameter = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblPerusahaan = new javax.swing.JLabel();
        lblPeriode = new javax.swing.JLabel();
        cboPerusahaan = new javax.swing.JComboBox();
        cboBulan = new javax.swing.JComboBox();
        cboTahun = new javax.swing.JComboBox();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Cost Performance");
        setResizable(false);

        pnlParameter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblJudul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("REPORT COST PERFORMANCE");
        lblJudul.setFocusTraversalPolicyProvider(true);

        lblPerusahaan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPerusahaan.setText("Perusahaan");

        lblPeriode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeriode.setText("Periode");

        btnProses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProses.setText("Proses");
        btnProses.setActionCommand("proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlParameterLayout = new javax.swing.GroupLayout(pnlParameter);
        pnlParameter.setLayout(pnlParameterLayout);
        pnlParameterLayout.setHorizontalGroup(
            pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addGroup(pnlParameterLayout.createSequentialGroup()
                            .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPerusahaan)
                                .addComponent(lblPeriode))
                            .addGap(29, 29, 29)
                            .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlParameterLayout.createSequentialGroup()
                                    .addComponent(cboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboTahun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addContainerGap(35, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParameterLayout.createSequentialGroup()
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        pnlParameterLayout.setVerticalGroup(
            pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParameterLayout.createSequentialGroup()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerusahaan)
                    .addComponent(cboPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriode)
                    .addComponent(cboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        CostPerformance report = null;
        try {
            DBConnection db = DBConnection.getInstances();
            db.configureConnection("config.properties");
            
            report = new CostPerformance(db.getConnection(), 
                            cboPerusahaan.getSelectedItem().toString(), 
                            cboBulan.getSelectedIndex() + 1, 
                            Integer.parseInt(cboTahun.getSelectedItem().toString()),
                            inisialPerusahaan[cboPerusahaan.getSelectedIndex()]);
            
            if(db.getConnection() != null){
                
                report.prosesOutputReport();
                log.info("Report Selesai Di Create dengan nama file \" " + CostPerformance.destFileName + " \"");
                JOptionPane.showMessageDialog(null, "Report Selesai. Silakan lihat hasilnya di \" " + CostPerformance.destFileName + " \" ", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            }
        } catch (ParsePropertyException ex) {
            log.error(ex.getMessage(), ex);
        } catch (IOException ex) {
            log.error(ex.getMessage(), ex);
        } catch (InvalidFormatException ex) {
            log.error(ex.getMessage(), ex);
        } catch(Exception ex){
            log.error(ex.getMessage(), ex);
        }
        
        if(report.isError()){
            JOptionPane.showMessageDialog(null,"Ada Error - Contact Prorammer Cek Log", "Information", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    
}//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportCost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ReportCost().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox cboBulan;
    private javax.swing.JComboBox cboPerusahaan;
    private javax.swing.JComboBox cboTahun;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPeriode;
    private javax.swing.JLabel lblPerusahaan;
    private javax.swing.JPanel pnlParameter;
    // End of variables declaration//GEN-END:variables

}
